### ISSUE TITLE
Image request

### ISSUE THREAD

**Issue by robmarkcole** [weichenrs/MFVNet#2]
Dear Wei
I would like to feature this work in my newsletter https://www.satellite-image-deep-learning.com/
I request a version of the image below from the paper, but without the red writing across it. Could you share?
Many thanks
Robin

<img width="963" alt="image" src="https://user-images.githubusercontent.com/11855322/225813369-ddc587e0-4e6f-427d-9ca7-f352f8f1c21d.png">

**Comment by weichenrs** [comment]
Sure. It has been uploaded.
